include: package:pedantic/analysis_options.1.9.0.yaml

linter:
  rules:
    nont_constatnt_identifier_names: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    prefer_relative_imports: false
    prefer_single_quotes: true
    prefer_void_to_null: true
    avoid_equals_and_hash_code_on_mutable_classes: false
